name: Deploy to WP Engine
on:
  # Only run when triggered manually.
  workflow_dispatch:

jobs:
  build:
    name: 📦  Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@v3
      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: 🏭 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: none, ctype, curl, date, dom, json, libxml, mbstring, phar, simplexml, soap, tokenizer, xml, xmlwriter, zlib
          coverage: none
          tools: none

      - name: Install dependencies with Composer
        run: ./tools/composer.phar update --no-dev --no-interaction --no-ansi --no-progress

      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: sbtweema
          FLAGS: --exclude-from=.deployignore

